---
name: Build

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - develop
    tags:
      - "release-*.*.*"
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    uses: metaborg/actions/.github/workflows/gradle-build-matrix.yaml@main
    with:
      gradle-command: |
        gradle buildAll --parallel --stacktrace
