---
name: 'Submit Dependencies'

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  build:
    uses: metaborg/actions/.github/workflows/gradle-dependencies.yaml@main
